//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaRamos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCita()
        {
            this.tblCitaDetalle = new HashSet<tblCitaDetalle>();
        }
    
        public int Id { get; set; }
        public string nombrePaciente { get; set; }
        public string apellidoPaciente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string tratamiento { get; set; }
        public string Estado { get; set; }
        public int IdMedico { get; set; }
    
        public virtual tblMedico tblMedico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCitaDetalle> tblCitaDetalle { get; set; }
    }
}
